/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDF2SVG
 #	author : miyako
 #	2015/08/01
 #
 # --------------------------------------------------------------------------------*/

#include <assert.h>
#include <stdlib.h>
#include <glib.h>
#include <poppler.h>
#include <poppler-document.h>
#include <poppler-page.h>
#include <cairo.h>
#include <cairo-svg.h>
#include <stdio.h>
#include <string.h>

typedef PA_long32 method_id_t;

// --- Convert
void PDF_Convert(sLONG_PTR *pResult, PackagePtr pParams);
void PDF_Get_page_count(sLONG_PTR *pResult, PackagePtr pParams);
